### ISSUE TITLE
v3 not on Packagist?

### ISSUE THREAD

**Issue by revoltek-daniel** [zeroseven/z7_semantilizer#22]
Hello looks like the v3 is not recognized by Packagist. 
https://packagist.org/packages/zeroseven/z7-semantilizer

Is it possible to trigger a update?

**Comment by schliesser** [comment]
![image](https://user-images.githubusercontent.com/11655823/159733391-aba5b090-b6ee-42d2-9c55-1137a7be4dc2.png)

**Comment by schliesser** [comment]
Fixed with:  https://github.com/zeroseven/z7_semantilizer/commit/43484d3525a1cf4c7a55d998252c1853b869b8ae

@raphaelthanner can you release v3.0.1 to make the extension accessible via packagist?

**Comment by raphaelthanner** [comment]
All right, done! Thanks very much!
