### ISSUE TITLE
Ignore the adminpanel

### ISSUE THREAD

**Issue by kaystrobach** [zeroseven/z7_semantilizer#27]
When the adminpanel is enabled the structure of the adminpanel is extracted:

![grafik](https://github.com/zeroseven/z7_semantilizer/assets/1185776/f373dbb5-607f-4c76-a232-067c671b411c)

Would be awesome if this would be ignored somehow.

**Comment by raphaelthanner** [comment]
We solved the problem in version 4.1.0
