### ISSUE TITLE
Semantilizer for V13

### ISSUE THREAD

**Issue by vb-benjamin-eyring** [zeroseven/z7_semantilizer#30]
Hi all, 

do you have plans to release semantilizer for V13? 

Thanks for a quick feedback
Benjamin

**Comment by vb-benjamin-eyring** [comment]
great, thanks for the quick update!

**Comment by raphaelthanner** [comment]
Hi @vb-benjamin-eyring (and the rest of the world),

you can check out version 4.2 now.

**Comment by vb-benjamin-eyring** [comment]
Thank you very much!
