### ISSUE TITLE
Is the extension supposed to work with multiple colPos?

### ISSUE THREAD

**Issue by ikonplant** [zeroseven/z7_semantilizer#6]
Is the extension supposed to work with multiple colPos?

If I use the extension with only one colPos, everything works fine.
As sooon as I use multiple colPos, I have an issue, that the extension works with the field "sorting", which depend on "colPos" Field. There is one more dependency (colpPos/sorting) which is not respectetd by the Extension

**Comment by schliesser** [comment]
We can verfiy this issue and will have a look into it.

Thanks for reporting

**Comment by schliesser** [comment]
@ikonplant We've just released v2.1.1 with support for multiple colPos.
Please check the readme section [here](https://github.com/zeroseven/z7_semantilizer/blob/master/README.md#colpos-ordering-for-backend-layouts) how to configure the new feature.

**Comment by srosskopf** [comment]
Closing this issue for lack of feedback and since the feature is now in the extension.
